services:
  # node-server:
  #   container_name: node
  #   build: .
  #   ports:
  #     - "8000:${BACKEND_PORT}"
  #   depends_on:
  #     - db
  #   environment:
  #     - PMA_HOST=${PMA_HOST}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_USER=${PMA_USER}
  #     - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - BACKEND_PORT=${BACKEND_PORT}
  try-js-db:
    image: mysql:latest
    container_name: try-js-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:${DB_PORT}"
  try-js-phpmyadmin:
    image: phpmyadmin:latest
    container_name: try-js-phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - try-js-db
